apiVersion: v1
kind: Service
metadata:
  name: numagui-proxy
spec:
  type: ClusterIP
  selector:
    app: numagui-proxy
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
