apiVersion: v1
kind: Service
metadata:
  name: numagui
spec:
  type: NodePort
  selector:
    app: numagui
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30001
